//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInfor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookInfor()
        {
            this.BookAuthors = new HashSet<BookAuthor>();
        }
    
        public string ProductID { get; set; }
        public Nullable<System.Guid> PublisherID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string ISBN13 { get; set; }
        public string LanguageID { get; set; }
        public string Introduction { get; set; }
        public string AuthorAbout { get; set; }
        public string Catalog { get; set; }
        public string Preface { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAuthor> BookAuthors { get; set; }
        public virtual Product Product { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
